# Generated by Django 3.2.5 on 2021-07-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='foreign_id',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventinstance',
            name='foreign_id',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventinstance',
            name='venue_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventinstance',
            name='venue_name',
            field=models.TextField(blank=True),
        ),
    ]
